<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CompensationAltimetrique.Core/CompensationAltimetrique.Core.csproj" />
    <ProjectReference Include="../CompensationAltimetrique.Calculations/CompensationAltimetrique.Calculations.csproj" />
    <ProjectReference Include="../CompensationAltimetrique.Data/CompensationAltimetrique.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="6.2.2" />
    <PackageReference Include="iTextSharp" Version="5.5.13.3" />
  </ItemGroup>

</Project>
